POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Marcelinho da Silva",
    "email": "mm@zinho.com",
    "password": "abc123"
}

###
GET http://localhost:3000/api/users

###
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "Mariazinha",
    "email": "ma@ma.com"
}

###
DELETE http://localhost:3000/api/users/1