POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "clayton@upf.br",
  "password": "abc123"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "clayton",
  "email": "clayton@upf.br",
  "password": "abc123"
}

###
GET http://localhost:3000/api/users
Authorization: Bearer ......
