POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "a",
  "email": "a"
}

###
GET http://localhost:3000/api/users

###
PUT http://localhost:3000/api/users/3
Content-Type: application/json

{
  "name": "Joana Doe",
  "email": "jojo@mana33.com"
}

###
DELETE http://localhost:3000/api/users/3

